[package]
name = "pliflo"
version = "1.2.2"
description = "A focused local document batch printing desktop app"
authors = ["Pliflo"]
edition = "2021"
license = "MIT"

[lib]
name = "pliflo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
canvas-cairo-replay = { path = "../crates/cairo-replay" }
serde.workspace = true
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
lopdf.workspace = true

[dev-dependencies]
serde_json.workspace = true
